Initialize
Zaida-3dO/goblin pull request #1
Opened 2022-04-09 22:36 UTC by Zaida-3dO

2022-04-09 22:37 UTC, bodolawale approved these changes

2022-04-09 23:18 UTC, leonardchinonso commented on hello.go
> +}
Run `gofmt -w .` in the current directory of a folder/file to format all Go code contained in that folder.
For this line for instance, it's supposed to end with a new line.
It's opinionated, I know :)

2022-04-09 23:19 UTC, leonardchinonso requested changes
Run `gofmt -w .` in the current directory of a folder/file to format all Go code contained in that folder.
For this line for instance, it's supposed to end with a new line.
It's opinionated, I know :)

2022-04-10 01:06 UTC, leonardchinonso approved these changes

2022-04-10 01:06 UTC, merged